### PR TITLE
pkgbuild revision

### PR DESCRIPTION
**Pull request by FabioLolix**
Hello,

* https://aur.archlinux.org/packages/aaregurucli-git/#comment-821398
* https://wiki.archlinux.org/title/VCS_package_guidelines#The_pkgver()_function
* https://wiki.archlinux.org/title/Go_package_guidelines#Flags_and_build_options

the pkgbuild also need a description in English which isn't the package name

### CODE REVIEW

**Comment by gexclaude** [comment]
@jon4hz may you have look?

**Comment by jon4hz** [comment]
Das isch e Grännicheib, d description isch i.O.

D pkgver function isch evt. nit best practice aber oh die funktioniert. Bi Glägeheit chani aber nomau drüberluege

**Comment by FabioLolix** [comment]
> Das isch e Grännicheib, d description isch i.O.
> 
> D pkgver function isch evt. nit best practice aber oh die funktioniert. Bi Glägeheit chani aber nomau drüberluege

Translated to English using deepl dot com

> That's a good thing, the description is OK.
> 
> The pkgver function may not be best practice but it works. But if you are lucky you can check it out again.

Correcting the description is OK, leaving as is is not OK.

The pkgver function is best practice, pasting pkgver=v0.5.0 is not

All these thing are also valid for the AUR pkgbuild, I have opend the issue here because @jon4hz  made some contributions here


***

About the release/pkgver what's going on that 0.50 is not being picked up by the pkgver and can't see the ac49f922dfba25908f23225dfcafe6731a2e4e5b commit?

aare002
aare001

**Comment by FabioLolix** [comment]
Hello again, do I need to fill an orphan request for a pkgbuild I have no interest to use or we can proceed with the revision?

**Pull request closed without merging**
